### ISSUE TITLE
Publish on the asset library.

### ISSUE THREAD

**Issue by fire** [tefusion/godot-subdiv#1]
Publishing to the asset library?

**Comment by tefusion** [comment]
I wanted to wait for the initial bugs, because I only tested the Linux Debug and this is my first addon. So tysm for testing right now :). I think I'll release it to the asset library at the end of the week.

**Comment by tefusion** [comment]
I'll put this on hold after all. I won't have time/no access to my computer to continue working on this for a few weeks and I don't want to publish something that can crash so easily.

**Comment by fire** [comment]
Ah, let me know when you’ll be back, in the meantime, I’ll try converting it back into a godot C++ module.

**Comment by tefusion** [comment]
> Ah, let me know when you’ll be back, in the meantime, I’ll try converting it back into a godot C++ module.

in ~2-3 weeks from now so not that long 

Port to a module will be very useful for more access in debugging and a better importer, so good luck with that if you have the time. Never did more than look at modules so no idea how well GDExtensions transfers to modules, my guess is mostly include paths and some special virtual GDExtension stuff would need to be changed/removed.

**Comment by fire** [comment]
I think we're ok for wider tests!

**Comment by tefusion** [comment]
> I think we're ok for wider tests!

🥳, thought so as well. I actually already opened a submission a few days ago but that one broke with beta 3. I'll create a new release 0.3.1 later after testing a bit more and update that submission then :)

**Comment by fire** [comment]
Let me know if you submitted.

**Comment by tefusion** [comment]
> Let me know if you submitted.

Updated it!

**Comment by tefusion** [comment]
🎉 Released to the asset lib https://godotengine.org/asset-library/asset/1488 🎉

I'll add a link to it on the info tab :)
