### ISSUE TITLE
Restore blender addon to export quad gltf.

### ISSUE THREAD

**Issue by fire** [tefusion/godot-subdiv#10]
Previously Facebook made an addon to allow quads to pass through from Blender.

I may be able to revive it and publish the extension as https://github.com/omigroup/gltf-extensions

**Comment by tefusion** [comment]
If its just quads I don't think an extra extension is necessary. Like, if it's not too much effort it'd be better than the current solution by a mile cause you could show the problematic faces, but in most cases the recreation by merging vertices should work (you have to actively try to break it, like disconnecting a face so vertices overlap)

**Comment by fire** [comment]
I restored some old code. 

https://github.com/fire/glTF-Blender-IO/tree/OMI_ngon_encoding WIP: Does not export quads yet.

Old one that works on Blender 2.79 https://github.com/fire/glTF-Blender-IO/tree/FB_ngon_encoding

**Comment by fire** [comment]
Because of the other pr of enabling loop subdivide for trimeshes, this has less importance.
