### ISSUE TITLE
Remove quad_converter_post_import.gd?

### ISSUE THREAD

**Issue by fire** [tefusion/godot-subdiv#14]
Is quad_converter_post_import.gd necessary after the import changes?

[quad_converter_post_import.gd](https://github.com/tefusion/godot-subdiv/blob/main/project/addons/godot_subdiv/quad_converter_post_import.gd)

**Comment by tefusion** [comment]
You're right, might give some confusion. I'll update the ReadMe when I'm done with baking with a better explanation for the importer. Reason for creating it was cause Godot always disabled the custom importer when errors were thrown and I needed to change it back which forced a godot restart which happened a lot early on.

**Comment by tefusion** [comment]
It might still be useful though. In the fancy advanced import settings window there's a lot more options that can't be used by a custom importer script or can they?

Edit: nvm there’s EditorScenePostImportPlugin

**Comment by tefusion** [comment]
Done with 39847c796bc3255f058229bc10f392829d1f924f. Now added an EditorScenePostImportPlugin that actually preprocesses the import, so this really isn't needed anymore. If I can think of a better name for that class I'll open a proposal in Godot for a name change. I always skipped over this  thinking it was just a slightly more powerful EditorScenePostImport not something completely different.

**Comment by fire** [comment]
horray!
