### ISSUE TITLE
Extend MeshInstance3D and Mesh.

### ISSUE THREAD

**Issue by tefusion** [tefusion/godot-subdiv#16]
Core changes needed:

- Callback for the set_base calls in MeshInstance3D to be able to set the correct base at the correct moment.
- set_blend_shape value virtual
- Access to internal skeleton

**Comment by fire** [comment]
I think this is completed.

**Comment by fire** [comment]
I think this is good enough as is. Ok to close?

**Comment by tefusion** [comment]
> I think this is good enough as is. Ok to close?

Yeah, current solution works pretty well imo
