### ISSUE TITLE
Crashes on beta 3

### ISSUE THREAD

**Issue by fire** [tefusion/godot-subdiv#17]
On windows and testing https://github.com/tefusion/godot-subdiv/commit/39847c796bc3255f058229bc10f392829d1f924f on beta 3 crashes when running subdiv 2 on fox.

https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Fox/glTF-Binary/Fox.glb

**Comment by fire** [comment]
I tested the below three and it worked, but not fox.glb.:

[AnimatedMorphCube.glb](https://github.com/tefusion/godot-subdiv/blob/main/project/demo/AnimatedMorphCube.glb)
[skinning_test.glb](https://github.com/tefusion/godot-subdiv/blob/main/project/demo/skinning_test.glb)
[uv-test.glb](https://github.com/tefusion/godot-subdiv/blob/main/project/demo/uv-test.glb)

**Comment by tefusion** [comment]
Forgot another type check: Normal array is null and it tries to set it (one line change)
