### ISSUE TITLE
If the mesh is not indexed index it

### ISSUE THREAD

**Issue by fire** [tefusion/godot-subdiv#19]
https://github.com/tefusion/godot-subdiv/commit/b1a8cba7aed1fcb935991cf168cf053a760f4ee3#diff-d33d32e5c95b94168ba2419046959073375cd13d9c6d5dbd2956e67a50cfbb92R37

Might be another crash.

**Comment by fire** [comment]
Probably want to check if  p_mesh_arrays is sized ARRAY_MAX and all the requirements like vertex array existing is good.

**Comment by tefusion** [comment]
Should be fixed by dca566a11c5bc02e6c2eebce032ef548a211029e. I'll try some more glb test meshes later cause haven't found a mesh triggering this. the ARRAY_MAX check and vertex_array existing check are directly in the format generator which will just return 0.
