### ISSUE TITLE
Supports animation skinning?

### ISSUE THREAD

**Issue by fire** [tefusion/godot-subdiv#2]
One of my uses of subdiv was for skinned meshes like 3d characters.

**Comment by tefusion** [comment]
Could you elaborate what you mean with animation skinning? AFAIK animations just change the skeleton pose which should work in theory (haven't tested yet). Normal skinning is implemented within the QuadMeshInstance3D and calls an update for the subdivision mesh from there

**Comment by fire** [comment]
I misread the documentation. You support full skinning. Previously I was using cpu skinning.
