### ISSUE TITLE
Crash with float=64

### ISSUE THREAD

**Issue by fire** [tefusion/godot-subdiv#21]
Trying to enable float=64 for our build, but it's crashing.

Any idea how to debug it?

**Comment by tefusion** [comment]
I also struggled with debugging yesterday. I got it working with 87c4b391af1dbadeb9f0ee4b761d6eb95618d18d again on Linux, but last time I tried debugging didn't work for me at all on windows. My setup right now is compiling with 
```
"command": "scons",
            "group": "build",
            "args": [
                "target=template_debug",
                "dev_build=yes", //newly needed with beta 3, no optimization, but debug symbols
                "platform=linux",
                "-Q",
                "tests=1"
            ],
```
and for starting Godot still 
```
"program": "path/to/godot",
             "args": [
                "--verbose",
                "--editor",
                "--path",
                "${workspaceFolder}/project"
            ],
```

**Comment by fire** [comment]
I think this is the only thing we (V-Sekai) need to fix.

Been failing, but here is our branch. I have some patches, and a json api from our project. https://github.com/fire/godot-subdiv https://github.com/fire/godot-cpp/blob/a04709f4b57eb3dfab82a5b9e84318b749f744dd/godot-headers/extension_api.json

**Comment by fire** [comment]
Postponed til later for V-Sekai.
