### ISSUE TITLE
Compile time error with _create_topology_refiner

### ISSUE THREAD

**Issue by fire** [tefusion/godot-subdiv#22]
https://github.com/tefusion/godot-subdiv/blob/main/src/subdivision/subdivider.cpp#L103-L114

Channels is not initialized with a compile time constant.

**Comment by tefusion** [comment]
Is it throwing errors when compiling? Channels gets initialized with the call of _create_topology_descriptor. I just had to declare it in the refiner creation to avoid having to manually free and assign memory to it. It got freed when declared in the descriptor function.

**Comment by fire** [comment]
I think this is a fatal msvc compiler error.

I tried:

```c++
Far::TopologyRefiner *Subdivider::_create_topology_refiner(const int32_t p_level, const int32_t p_format) {
	const bool use_uv = p_format & Mesh::ARRAY_FORMAT_TEX_UV != 0;

	//create descriptor,
	Vector<int> subdiv_face_vertex_count;
	const int num_channels = use_uv ? 1 : 0;
	Vector<Descriptor::FVarChannel> channels;
	channels.resize(num_channels);
	Descriptor desc = _create_topology_descriptor(subdiv_face_vertex_count, channels.ptrw(), p_format);
```

Not sure if correct fix.

https://stackoverflow.com/questions/61739407/how-to-fix-this-code-for-giving-me-expression-did-not-evaluate-to-a-constant

Stackoverflow said the other way is:

```c++
int* a = new int[n];
// Free sometime in future. Unknown timeframe.
```

**Comment by tefusion** [comment]
I don't think a vector is necessary here cause we don't need to resize at all. I went with the second solution you provided and that worked well for me (on windows, beta 3. I'll update to 4 later). 

Thanks!
