### ISSUE TITLE
Use triangular patches to avoid converting from quads.

### ISSUE THREAD

**Issue by fire** [tefusion/godot-subdiv#3]
https://graphics.pixar.com/opensubdiv/docs/release_34.html#triangular-patches-for-loop-subdivision

**Comment by tefusion** [comment]
I do plan to add loop subdivision. I still think quads are better though when possible. My main problem with loop subdivision was the uneven placement of faces. Seems less severe in those example images though

**Comment by fire** [comment]
Previously the loop operator trashed this model. Not sure now.

https://sketchfab.com/3d-models/pony-cartoon-885d9f60b3a9429bb4077cfac5653cf9

The headlamp would be corrupted.

The arrows point to the texture seam without subidivision. 
![image](https://user-images.githubusercontent.com/32321/188507036-557e3494-5cc7-4ed7-b467-553608fc78bb.png)

**Comment by tefusion** [comment]
Done with a8602ee5225e8c4ce449a28a22edd4b09d821959. I also tried the example model and the result looked pretty okay to me (level 3): 
![TriangleSubdivision](https://user-images.githubusercontent.com/69000267/193404464-7fa1b343-c7b9-4865-b730-cc00af13f471.jpg)

Some textures near the window and the side of the model still get corrupted/bad results, maybe opensubdiv has some more settings to use to avoid that
