### ISSUE TITLE
Document how to create a quad only gltf2

### ISSUE THREAD

**Issue by fire** [tefusion/godot-subdiv#6]
Create a glb/gltf file that contained only quads.

**Comment by tefusion** [comment]
Just the way it says. For checking that you don't have any ngons left: In blender you can go into edit mode and go in the top bar select->select all by trait->select faces by sides and set the setting to not equal to 4

**Comment by fire** [comment]
Would be good to add to the readme.

**Comment by tefusion** [comment]
Added in 8433deca451fdaec3515df8b0e28cafd555e7d6c.
